- hosts: ca_server
  vars:
    easy_rsa_req_country: "ID"
    easy_rsa_req_province: "KA"
    easy_rsa_req_city: "Jakarta"
    easy_rsa_req_org: "Example"
    easy_rsa_req_email: "admin@example.com"
    easy_rsa_req_ou: "Example"
    easy_rsa_local_pool_directory: /tmp/ca_openvpn_pool_example
    easy_rsa_ca_server_mode: true
  roles:
    - role: gavika.easy_rsa
