apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTdIWXRhM2lIb0xmdTFZNDI2Z0x5NG0vTitIdjlTd2xEM0xjRC9JZXlGbksvCmxaR3FVdHJkeDR2aDNHcXd1RjAxM0RVdWo3TFV0eTMzYzVlWGRkOHk0MDhZNEY4aFFJV0QvN2pGWWlmcmgwQ1oKUGpsSllLbmF0alFCazhMb3dQMFB5V3l3aGNXNzNjWDR0Ri9nNmUzdDJKalhxWXlRNUlSRm91blgzOFBzbGptUwpIQjJsQmVTUVpDNlVURzR2SkZnOHdoblA3cXR5dFNkZll0VUtJM0xhcEhGVkdFQmx5a285NkhBclZsQ1F6QW9pCjhwVHNOVTc5eEdvNWphZUVsOE1TNlRPYmUxeW1mMFRKWi9EamJVNnhTVXBFaHlJOHBkbDhUaThxTFdLU3c4cUkKN1dQU0NESTJCVUdDVU1OZEo4ZlAzMm9LOTNsY011YUZLTDk4UHBOSDNRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBTHEzODFyVWdpbThQQS9lY0piU01nZjg0UVB5dW1CaXBtOEZHRzMyRGRUcFRHd1JVWDNMCkxIeVFMVFVmT2QrQk5WdkJIYjhoMXQxNUFkeVdKbkN6Nk0wZ3hEei9YNXZUWkpwN1UreXZDaXQ2b25uMVhzcE4KKzgrcmtTZjZBeCtpWHVwci90REg1Y1E2SDV5T3ZUeXA3aUp3VVdPOWVWS3JMdkdtQVZSb09IOGg5cTExZ2d5ZgpQclcxVFZNcFhHZ2tsVUxIaFhibzByZXBOcDZ0TXBaMGZXa1MxeHdjaTc3ek5MdCtJVTF3ZU8zMlpOVDF1NkhUCmdNN2FNdERzNEF3TXkxU2VjMFZNVnJ5WFA5OVhJZnN6UllqWFJOblhuK2pZVVRldnBsVlYvNSt5czhwcHl4Q1cKWXhDSU8zVEZ1cHoxSlNtb0xBdUJyNTdlaWJjV2hPbFVLYTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth
  