cat /etc/kubernetes/manifests/kube-apiserver.yaml

//open certificate
openssl x509 -in /etc/kubernetes/pki/apiserver.crt -text -noout

//to see Logs with kubectl
kubectl logs etcd-master

//to see logs with docker
docker ps
docker logs 2323D

// get list of certificate
kubectl get csr

//approve certificate
kubectl certificate approve <name>

//extract yaml of certificate request
kubectl get csr agent-smith -o yaml

//change context to user prod-user in cluster production
kubectl config use-context prod-user@production