apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: blue
rules:
- apiGroups: ["apps","extensions"]
  resources: ["pods","deployments"]
  verbs: ["list","create"]
