//role binding
kubectl get rolebindings

//describe role
kubectl describe role developer

//check access
kubectl auth can-i create deployments
kubectl auth can-i delete nodes

//check access as users
kubectl auth can-i create deployments --as dev-user
kubectl auth can-i delete nodes --as dev-user

// and look for --authorization-mode
kubectl describe pod kube-apiserver-master -n kube-system
