#!/bin/bash
#get the date
date=$(date)
topic="$1"
pwddata="${PWD}"
filename="${pwddata}/${topic}notes.txt"

read -p "Your note: " note

if [[ $note ]]; then
  #statements
  echo "$date: $note" >> "$filename"
  echo "Note '$note' saved in $filename"

else  #statements
  echo "no input" 1>&2
fi
